export const SOCKETS_CONNECTING = "SOCKETS_CONNECTING";

export const SOCKETS_DISCONNECTING = "SOCKETS_DISCONNECTING";
export const SOCKETS_MESSAGE_SENDING = "SOCKETS_MESSAGE_SENDING";
export const SOCKETS_MESSAGE_RECEIVING = "SOCKETS_MESSAGE_RECEIVING";
export const SOCKETS_PRODUCT_RECEIVING = "SOCKETS_PRODUCT_RECEIVING";
export const LIKE_COMMENT = "LIKE_COMMENT";

export const START = "_START";
export const SUCCESS = "_SUCCESS";
export const FAIL = "_FAIL";
