export const SOCKETS_CONNECTING = "SOCKETS_CONNECTING";
export const SOCKETS_DISCONNECTING = "SOCKETS_DISCONNECTING";
export const SOCKETS_MESSAGE_SENDING = "SOCKETS_MESSAGE_SENDING";
export const SOCKETS_MESSAGE_RECEIVING = "SOCKETS_MESSAGE_RECEIVING";
